language: node_js
node_js:
- '6'
script: npm test
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: KSkWvql83tN38gNJVKsHwNZkERSuzFPWWJ8jtJ9TQ3rTD3caAm64p4B6x1AK1GBviZae871PSHx3BVghMhfxGqnNh1oolruOt3YE2ynpXN5vQHbpp741qirSaSJlnF5Ipw897zeUi5wHs8/7hYq6I1PhXa6FmCQOnrucVvVbZkg=
  on:
    tags: true
    repo: noflo/noflo-xpress
